### ISSUE TITLE
No such file or directory: '/Users/danil/OneDrive/...'

### ISSUE THREAD

**Issue by dnnshaun** [DanilZherebtsov/verstack#15]
Hello Danil

I just did a `pip install verstack`  and when I try to the the NaNImputer, when I get this message.
Using a Jupyter notebook.

The Factorizer file looks a little messed up to me or am I just "holding it wrong"?

```
FileNotFoundError                        Traceback (most recent call last)
<ipython-input-21-36b05ef79f67> in <module>
     71 
     72 
---> 73 from verstack import NaNImputer


FileNotFoundError: [Errno 2] No such file or directory: '/Users/danil/OneDrive/Bell/datasets/_traditional/house_prices (rmsle,Id,SalePrice)/house_prices_train.csv'
```

**Comment by DanilZherebtsov** [comment]
Sorry for that. I have forgotten to remove the testing code before publishing a release. Now it's all set. Just `pip install --upgrade verstack`
New version is 2.0.11.

**Comment by dnnshaun** [comment]
Thanks for the fix and all the work you've done. Much appreciated.

Prior to trying the latest version I deleted the test harness code you'd accidentally left in the Factorizer class and ran it locally like that - it worked ok EXCEPT, it complained about a dependency `mlxtend` that was missing. I just pip installed that and it all worked fine. I'm guessing  the problem with `mlxtend` was that it's not listed as a dependency for this package? I don't know much about python or pip so I'm just taking a guess here but you might want to check that at some stage.

Thanks again for all the hard work you've put into this package!

**Comment by DanilZherebtsov** [comment]
Good call, thank you. Updated dependencies with `mlxtend`.
