### ISSUE TITLE
latest tensorflow not possible?

### ISSUE THREAD

**Issue by csetzkorn** [DanilZherebtsov/verstack#17]
When I do:

`pip install verstack==3.2.1`

to force latest version, I get:

```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.0 (from verstack) (from versions: 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1)
ERROR: No matching distribution found for tensorflow==2.7.0
```

Can this package not work with latest tensorflow?

**Comment by DanilZherebtsov** [comment]
I see two issues here:
1. At install verstack is supposed to pull the specified version of TensorFlow (verstack depends on 2.7.0). In your case it should override the installed version by 2.7.0. Does this not happen.
2. I generally like to keep verstack updated to the latest technologies. In chis case I will be able to integrate the latest TensorFlow version support only after testing. This will take another day.
While I will get back to you on issue number 2, please comment on issue 1.

**Comment by csetzkorn** [comment]
Thanks for the reply. Yes w.r.t. 1.

**Comment by DanilZherebtsov** [comment]
Latest versions of dependencies are supported, along with python up to 3.10
Now works with the latest TF/Keras 2.11.0

`$ pip install --upgrade verstack`
you should get version 3.3.3
