### ISSUE TITLE
LGBMTuner GPU support

### ISSUE THREAD

**Issue by pavlexander** [DanilZherebtsov/verstack#21]
When training model in vanilla LGBM you could specify the target `device` to be `GPU`

```py
model = LGBMClassifier(
    device="gpu",
)
```

However, when running the model with `LGBMTuner` I do not see such option. Upon launch of the `fit()` - `CPU` utilization spikes to 100%.. Is there any way to make the program utilize `GPU`? Could you document it?

![image](https://user-images.githubusercontent.com/20644772/200143968-0d246937-deb2-4457-82d5-c75c9fdb114e.png)

**Comment by DanilZherebtsov** [comment]
Thank you for a great comment. Just added GPU support.
At init you can specify the device_type keyword argument as of of the following: 'cpu', 'gpu', 'cuda', 'cuda_exp'
```
tuner = LGBMTuner(metric = 'auc', device_type = 'gpu')
```

Just update the package to a latest 3.3.0 version:
```
$ pip install --upgrade verstack
```
