### ISSUE TITLE
Updating requirements

### ISSUE THREAD

**Issue by najeeb9522** [DanilZherebtsov/verstack#22]
Is it possible to get the `requirements.txt` updated to newer version of scikit-learn, lightgbm, plotly, python-dateutils?

I have used the FeatureSelector with the manually updated versions of the above packages and it worked without any hiccup. Other DS packages usually look for comparatively newer packages and installing verstack always gives a dependency error

**Comment by DanilZherebtsov** [comment]
I will have to check how other modules will react behave under the new dependencies, but generally - Yes, I like to keep the dependencies updated. I will launch unit tests with the latest versions of the mentioned packages and if all goes well, you can update verstack tomorrow. Will post the results upon testing completion.

**Comment by DanilZherebtsov** [comment]
Latest versions of dependencies are supported, along with python up to 3.10

`$ pip install --upgrade verstack`
you should get version 3.3.3

**Comment by najeeb9522** [comment]
Perfect, thank you so much
