### ISSUE TITLE
CNN on surgical site infection

### ISSUE THREAD

**Issue by chrissny88** [DanilZherebtsov/verstack#25]
Hello,

I want to build a deep learning model that can predict if a surgical wound (delivery by cesarean section) is infected or not. attached is the  sample images.
1.What pre trained model will you advise for transfer learning ?
2. What will be the best image format to work with between LAB,RGB an HSV

![wound images](https://user-images.githubusercontent.com/94523190/207919138-9a466935-b56f-4952-badd-e75e51833e72.jpg)

**Comment by DanilZherebtsov** [comment]
Hi,

IMHO you should use the RGB images since the color makes logical sense in this project.
Regarding the pertained models - I cannot advise. This is some specific task, google...

**Comment by chrissny88** [comment]
noted. thanks
