### ISSUE TITLE
Customizing search space for LGBMTuner

### ISSUE THREAD

**Issue by dcapeluto** [DanilZherebtsov/verstack#28]
The default search space seems limited for several use cases. I've trained models before in which Optuna yielded num_leaves = 1700, yet Verstack seems not going above 300 for the same data.

Is it possible to customize the search space?

**Comment by DanilZherebtsov** [comment]
Hi @dcapeluto 
The requested fix is pushed with the new version of verstack (3.7.0).
Now you can define various custom LGBM parameters for tuning within LGBMTuner.

$pip install --upgrade verstack

The new options are reflected in the documentation: https://verstack.readthedocs.io/en/latest/#id16
and in the medium article: https://danilzherebtsov.medium.com/effortlessly-tune-lgbm-with-optuna-49de040d0784

**Comment by dcapeluto** [comment]
Awesome!
