### ISSUE TITLE
How to forward some fixed arguments to LGBMClassifier?

### ISSUE THREAD

**Issue by leonleeann** [DanilZherebtsov/verstack#33]
I'm using verstack.LGBMTuner to optimize params of a lightgbm.LGBMClassifier, that should resolve a multiclass classification problem.

My trouble is that the dataset is heavily imbalanced, so I need pass an argument `class_weight='balanced'` to LGBMClassifier's constructor.

I read the docs of LGBMTuner, but I didn't find any hint about how to forwarding parameters to a potential estimator.

Is there a way I can do it?

**Comment by DanilZherebtsov** [comment]
Hi @leonleeann 

Thank you for your comment. I've had this feature request quite a few times by now and just shipped the update.

pip install --upgrade verstack

You should get a verstack.__version__ == 3.8.0 and LGBMTuner.__version__ == 1.1.0

Now you can pass any supported LGBM parameters at init as follows:

```
from verstack import LGBMTuner

my_custom_params = {'class_weight' : 'balanced'}

tuner = LGBMTuner(metric = 'accuracy', custom_lgbm_params = my_custom_params)

It is all reflected in the documentation.

**Comment by DanilZherebtsov** [comment]
> Thank you @DanilZherebtsov !
> Sorry, maybe I refered an outdated doc.

No, you were right. I just shipped the update today. Let me know if it works.
