### ISSUE TITLE
LGBM Tuner - Persistent studies 

### ISSUE THREAD

**Issue by JChapuyAuchan** [DanilZherebtsov/verstack#34]
Is it possible to add the possibility to make studies persistent (e.g. through optuna.create_study 'storage' parameter) ? 
Thank you in advance

**Comment by JChapuyAuchan** [comment]
I would like to pass the following parameters `storage, study_name`. Additionally it would be great to have a `load_if_exists`-like parameter / method to be able to reload a previous study.

On the reasons why I would need this: 
- using in-memory storage use to make my kernel crash with no possibility to recover parts of the study
- working with VMs I would like to easily transfer studies from one to another 
- easier historization

Let me know if you think `LGBMTuner` already has ways to deal with these points / if you feel like it is irrelevant

**Comment by DanilZherebtsov** [comment]
Done. Now you can pass any Optuna.study.create_study parameters according to the Optuna [docs](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.create_study.html).
Parameters are sent as a dictionary at LGBM.tuner(X, y, optuna_study_params). It is reflected in the updated verstack's documentation.

`$ pip install --upgrade verstack`

You should get version 3.8.8
