### ISSUE TITLE
Package does not work with M1 Mac because of Tensorflow version

### ISSUE THREAD

**Issue by najeeb9522** [DanilZherebtsov/verstack#36]
Verstack currently only supports TensorFlow 2.11.0 but support for M1 Macs was added to TensorFlow 2.13.0

**Comment by DanilZherebtsov** [comment]
Wow, that's some good news. Will update verstack shortly!

**Comment by DanilZherebtsov** [comment]
Done. Tensorflow 2.13 now supported in verstack

$`pip install --upgrade verstack`
