### ISSUE TITLE
Documentation: problem on the first page

### ISSUE THREAD

**Issue by ibobak** [DanilZherebtsov/verstack#39]
if we open the link https://verstack.readthedocs.io/en/latest/
we will see on the first page "veratack package contains the following tools"

Looks like a wrong name.

**Comment by DanilZherebtsov** [comment]
I've just checked - the link seems to be working correctly. 
Try a different browser, try from your mobile (disconnected from wifi) just to doublecheck.

**Comment by ibobak** [comment]
![image](https://github.com/DanilZherebtsov/verstack/assets/8807043/291e96ad-0bfd-42a4-b502-de30f5c4077a)

**Comment by DanilZherebtsov** [comment]
Good catch! It's verstack. I will correct the documentation.

**Comment by DanilZherebtsov** [comment]
Did you manage to see all the docs?

**Comment by ibobak** [comment]
Sure.

**Comment by DanilZherebtsov** [comment]
> ![image](https://private-user-images.githubusercontent.com/8807043/331603060-291e96ad-0bfd-42a4-b502-de30f5c4077a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjQ5MzcsIm5iZiI6MTcxNTk2NDYzNywicGF0aCI6Ii84ODA3MDQzLzMzMTYwMzA2MC0yOTFlOTZhZC0wYmZkLTQyYTQtYjUwMi1kZTMwZjVjNDA3N2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMTY1MDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA2YTRhNGJmZjFhZmMwMGQ0MTAxZGIyNzBhNWM3YjgzMTVkMDk5ZTAwNTI1NmI4ODYyYzYxODdmNTE5ZTFmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pPLXffB5HBX0tRvlZ3FR8ivEZt5PiPwSylGo_qGvieE)

fixed it, thanks!

![CleanShot 2024-05-20 at 10 08 43@2x](https://github.com/DanilZherebtsov/verstack/assets/35999411/6d71fa86-b600-4d12-9b61-3b8e3bbb8ab3)
