### ISSUE TITLE
UFuncTypeError

### ISSUE THREAD

**Issue by soumitra9** [DanilZherebtsov/verstack#4]
I am getting the following error on using:

X_train, X_test, y_train, y_test = scsplit(X, y, stratify=y)

Inputs are all pandas dataframes.
UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

**Comment by DanilZherebtsov** [comment]
Could you please share a data sample or some code to recreate your Dataframe?
