### ISSUE TITLE
Converting string from to UTF-8 after installation of iTerm

### ISSUE THREAD

**Issue by Richynor** [DanilZherebtsov/verstack#40]
iconv: iconv_open(, -t): Invalid argument
Error converting string from  to UTF-8

**Comment by DanilZherebtsov** [comment]
> iconv: iconv_open(, -t): Invalid argument
> 
> Error converting string from  to UTF-8

Hi. You get this error installing verstack?

**Comment by DanilZherebtsov** [comment]
Oh, so this is about an iTerm2 setup video. Right?

If so then you must have made an error somewhere in your .zshrc file. Have you followed the manual in the video precisely?

**Comment by Richynor** [comment]
Fixed it. Thank you Danil!

**Comment by DanilZherebtsov** [comment]
> Fixed it. Thank you Danil!

What was the problem?

**Comment by Richynor** [comment]
There was a typo issues in .zshrc file.
