### ISSUE TITLE
from verstack import NaNImputer

### ISSUE THREAD

**Issue by jcruelasgarcia** [DanilZherebtsov/verstack#47]
Hello, Danil.

Just followed your tutorial: https://youtu.be/QcMAHnHlIKk?si=oiO0JAexsjXsfd8c

I created a fresh 3.9 python virtual environment with your instructions.

While running:

`from verstack import NaNImputer`

I get the following error:

OSError: dlopen(/Users/juan/.pyenv/versions/proj_mst_3.9/lib/python3.9/site-packages/lightgbm/lib/lib_lightgbm.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib
  Referenced from: <3B4502C7-E247-32FC-8586-FB4DB2322E21> /Users/juan/.pyenv/versions/3.9.20/envs/proj_mst_3.9/lib/python3.9/site-packages/lightgbm/lib/lib_lightgbm.dylib
  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/Users/juan/.pyenv/versions/3.9.20/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/juan/.pyenv/versions/3.9.20/lib/libomp.dylib' (no such file), '/opt/homebrew/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libomp.dylib' (no such file), '/Users/juan/.pyenv/versions/3.9.20/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/juan/.pyenv/versions/3.9.20/lib/libomp.dylib' (no such file), '/opt/homebrew/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libomp.dylib' (no such file)

I have ligthgbm instlled (through pip) and couldn't find the nature of the problem.

Would appreciate your insight.

Thank you very much.

**Comment by DanilZherebtsov** [comment]
Hi jcruelasgarcia.

I have recently updated `verstack` to run on python 3.9 - 3.12 with all the latest dependencies versions.

I advice you to switch to python3.12 environment, uninstall `lightgbm` and `pip install verstack` (it will pull the latest `lightgbm` version as well).

Let me know how it went.

**Comment by jcruelasgarcia** [comment]
Thank you for your prompt response!

I did a fresh install of a 3.12 virtual environment, however I keep running into the same issue:

OSError: dlopen(/Users/juan/.pyenv/versions/proj_mst_3.12/lib/python3.12/site-packages/lightgbm/lib/lib_lightgbm.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib
  Referenced from: <D3923ACB-D836-32D3-A031-CF91999FDAFC> /Users/juan/.pyenv/versions/3.12.6/envs/proj_mst_3.12/lib/python3.12/site-packages/lightgbm/lib/lib_lightgbm.dylib
  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/local/lib/libomp/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libomp/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/local/lib/libomp/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libomp/libomp.dylib' (no such file), '/Users/juan/.pyenv/versions/3.12.6/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/juan/.pyenv/versions/3.12.6/lib/libomp.dylib' (no such file), '/opt/homebrew/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libomp.dylib' (no such file), '/Users/juan/.pyenv/versions/3.12.6/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/juan/.pyenv/versions/3.12.6/lib/libomp.dylib' (no such file), '/opt/homebrew/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libomp.dylib' (no such file)

Perhaps there is something I am ignoring?

Thank you and apologies for the inconvenience

**Comment by DanilZherebtsov** [comment]
try this before installing `verstack`

`brew install libomp`

**Comment by jcruelasgarcia** [comment]
Many thanks, Daniel.

That was it.

Huge fan of your videos.

Keep up the good work.

**Comment by DanilZherebtsov** [comment]
Thanks!!
