### ISSUE TITLE
error running on m1 Mac

### ISSUE THREAD

**Issue by rockml** [DanilZherebtsov/verstack#8]
Running on silicon Mac I was able to install verstack, but running first example of multicore produced this error:

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

This occurred once for each of the 8 core it was trying to use

**Comment by DanilZherebtsov** [comment]
I have not tested this on M1 architecture, but I am not sure this is platform specific.
Could you share data and function to reproduce the error?

If not, then you can try the two approaches on the dummy code below:
Approach 1 (if you are executing function one by one in the console):

```

def square(n):
    # Real hard work here
    return n**2

iterable = range(0,100)

from verstack import Multicore
worker = Multicore()
result = worker.execute(square, iterable)
print(result)
```

Approach 2 (save this into a separate .py file and run in from the terminal: $ python file_name.py) :
```
def square(n):
    # Real hard work here
    return n**2

def perform_square_using_verstack():
    iterable = range(0,100)
    
    from verstack import Multicore
    worker = Multicore()
    result = worker.execute(square, iterable)
    print(result)
    
if __name__ == '__main__':
    perform_square_using_verstack()
```

Let me know if it works.
