### ISSUE TITLE
a question about multicore

### ISSUE THREAD

**Issue by harplife** [DanilZherebtsov/verstack#9]
Hello, I read this [article](https://danilzherebtsov.medium.com/parallelise-like-a-boss-with-a-single-line-of-code-in-python-30af0d640511) and I tried the code example(s) for iterating over a single object. I tried two different versions and the time difference is quite significant - which leads to my question, why?

Environment:
 - Windows 10 Pro
 - Python 3.7.4

code example 1 (result : 0.8 seconds)
```python
data = range(0,1000000)

def exponential(n):
    # Real hard work here
    return n**2

def execute_func_using_verstack(func,iterable):
    from verstack import Multicore
    worker = Multicore()
    result = worker.execute(func, iterable)

if __name__ == '__main__':
    execute_func_using_verstack(exponential, data)
```

code example 2 (result : 2.26 seconds)
```python
from verstack import Multicore
worker = Multicore()

data = range(0,1000000)

def exponential(n):
    # Real hard work here
    return n**2

if __name__ == '__main__':
    result = worker.execute(exponential, data)
```

The time difference is nearly 4 times.
Is this specific to Python 3.7.4 (on Windows)?
Or is this specific to my computer?
I'm just curious.

From what I could observe so far, it seems like the python file is executed n times (n = number of workers),
except for the `execute_func_using_verstack()` function and whatever's under `if __name__ == '__main__'`.
You can see that happening, with
```python
data = range(0,1000000)

print('engaging')

def exponential(n):
    # Real hard work here
    return n**2

def execute_func_using_verstack(func,iterable):
    from verstack import Multicore
    print('working')
    worker = Multicore()
    result = worker.execute(func, iterable)

if __name__ == '__main__':
    print('starting')
    execute_func_using_verstack(exponential, data)
```
resulting in
```
engaging
starting
working
Multicore(workers = 8,
          multiple_iterables = False

Initializing 8 workers for exponential execution
engaging
engaging
engaging
engaging
engaging
engaging
engaging
engaging
```

This means that if I do all the imports at the top, it will be executed 8 times, resulting in slow time.
Is this intended behavior?

Let me know if there are other information you want me to provide.
Also, great work!

**Comment by DanilZherebtsov** [comment]
Thank you for all the experiments. One thing stands out - you have 8 prints of '#### engaging #####' in all of your attempts. And this print should have only been printed once...
It appears that the code could have been run 8 times
